version: "3"

networks:
  the-black-network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - the-black-network

  webapp:
    container_name: webapp
    stdin_open: true
    tty: true
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: the-black-webapp
    ports:
      - "3000:3000"
    volumes:
      - ./webapp/src:/usr/src/app/src
      - /usr/src/app/node_modules
    networks:
      - the-black-network
